dist: xenial

language: generic

addons:
  apt:
    sources:
    - sourceline: 'ppa:octave/stable'   ## without this, it's octave 4.0.0
    packages:
    - liboctave-dev
    - octave        # octave 4.2.2
    update: true
  homebrew:
    packages:
    - octave        # octave 5.1.0
    update: true
os:
- linux
- osx

install:
- git clone --depth=50 https://github.com/MATPOWER/mptest.git $TRAVIS_BUILD_DIR/mptest

env:
  global:
    - MPTEST_PATH=$TRAVIS_BUILD_DIR/mptest/lib:$TRAVIS_BUILD_DIR/mptest/lib/t
    - MIPS_PATH=$TRAVIS_BUILD_DIR/lib:$TRAVIS_BUILD_DIR/lib/t:$MPTEST_PATH

script:
- octave-cli --no-gui --eval ver
- octave-cli --no-gui -p $MPTEST_PATH --eval mptestver
- octave-cli --no-gui -p $MPTEST_PATH --eval "test_mptest(0,1)"
- octave-cli --no-gui -p $MIPS_PATH --eval mipsver
- octave-cli --no-gui -p $MIPS_PATH --eval "test_mips(0,1)"
